name: Clone Master To QA

on:
  push:
    branches:
      - master

jobs:
  clone-to-qa:
    name: Clone Master To QA
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    steps:
      run: |
        git branch --delete qa && git checkout -b qa && git push origin qa
