name: Clone Master To QA

on:
  push:
    branches:
      - master

jobs:
  clone-to-qa:
    name: Clone Master To QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch && git checkout qa && git checkout master && git push -d origin qa && git branch -d qa && git checkout -b qa && git push origin qa
